package suite_test

// Tests for RunIDGenerator: collision-free run identity under a frozen clock,
// format-validator conformance, idempotent lookup, and concurrent-use safety.
//
// These tests fail to compile until RunIDGenerator, NewRunIDGenerator and
// MaxRunsPerSuite are defined in the suite package — that is the TDD RED
// phase. Define those types (I13.1) to make the tests compile; implement them
// correctly to make the tests pass.

import (
	"fmt"
	"sync"
	"testing"

	"mosaic-agent-test/internal/domain"
	"mosaic-agent-test/internal/suite"
)

// TestRunIDGenerator_UniqueAcrossFullMatrix_UnderFrozenClock drives a matrix
// well beyond any realistic suite against a clock that never advances. Every
// identity in the whole (test × repetition × attempt) matrix must be distinct.
//
// The residual exposure of the hash-based approach — a 16-bit birthday
// collision across the matrix within one timestamp second — grows as
// concurrency puts more of the matrix inside one second. The ordinal approach
// eliminates it: distinct tuples get distinct ordinals by construction, so the
// collision probability is not "low" but zero.
func TestRunIDGenerator_UniqueAcrossFullMatrix_UnderFrozenClock(t *testing.T) {
	const (
		numTests    = 50
		repetitions = 10
		attempts    = 2
	)

	clock := newFakeClock() // frozen — Now() always returns the same instant
	g := suite.NewRunIDGenerator(clock)

	total := numTests * repetitions * attempts
	seen := make(map[string]struct{}, total)

	for testIdx := 0; testIdx < numTests; testIdx++ {
		testID := fmt.Sprintf("test-%03d", testIdx)
		for rep := 1; rep <= repetitions; rep++ {
			for attempt := 0; attempt < attempts; attempt++ {
				id := g.Next(testID, rep, attempt)
				if _, dup := seen[id]; dup {
					t.Errorf("identity collision: Next(%q, %d, %d) = %q was already generated by a different tuple", testID, rep, attempt, id)
				}
				seen[id] = struct{}{}
			}
		}
	}

	if got := len(seen); got != total {
		t.Errorf("expected %d unique identities, got %d — some were missing or duplicated", total, got)
	}
}

// TestRunIDGenerator_AllIDsSatisfyFormatValidator asserts that every identity
// the generator produces passes domain.ValidRunID. The logger bundle silently
// buckets anything that does not match the pattern under an unknown-run bucket;
// cost attribution then fails for a reason no message names. A test is the
// only thing that makes that failure mode explicit rather than discovered in
// production.
func TestRunIDGenerator_AllIDsSatisfyFormatValidator(t *testing.T) {
	clock := newFakeClock()
	g := suite.NewRunIDGenerator(clock)

	cases := []struct {
		testID  string
		rep     int
		attempt int
	}{
		{"single", 1, 0},
		{"multi-test", 5, 1},
		{"first-attempt", 1, 0},
		{"retry-attempt", 1, 1},
		{"large-ordinal", 100, 1},
		{"many-reps", 99, 0},
	}

	for _, tc := range cases {
		id := g.Next(tc.testID, tc.rep, tc.attempt)
		if !domain.ValidRunID(id) {
			t.Errorf(
				"Next(%q, %d, %d) = %q does not satisfy domain.ValidRunID — "+
					"the logger bundle would silently bucket this run under unknown-run "+
					"and cost attribution would fail for a reason no message names",
				tc.testID, tc.rep, tc.attempt, id,
			)
		}
	}
}

// TestRunIDGenerator_SameTupleReturnsSameID verifies that calling Next twice
// with the same (testID, runNumber, attempt) tuple returns the same identity.
// A lookup must never allocate a second ordinal: two different identities for
// the same logical run would write into two different log folders and neither
// would accumulate complete cost evidence.
func TestRunIDGenerator_SameTupleReturnsSameID(t *testing.T) {
	clock := newFakeClock()
	g := suite.NewRunIDGenerator(clock)

	const testID = "stable-test"

	first := g.Next(testID, 1, 0)
	second := g.Next(testID, 1, 0)

	if first != second {
		t.Errorf(
			"Next(%q, 1, 0) returned %q then %q — the same tuple must always return "+
				"the same identity; a second allocation corrupts cost attribution",
			testID, first, second,
		)
	}
}

// TestRunIDGenerator_RetriedAttemptGetsDistinctIdentity verifies that
// attempt 0 and attempt 1 for the same (testID, runNumber) pair produce
// different identities. The retry path exists because attempt 0's sandbox may
// hold corrupted state; giving the retry the same identity as the original
// attempt would map it to the same sandbox and the same log folder — the very
// corruption the retry is meant to escape.
func TestRunIDGenerator_RetriedAttemptGetsDistinctIdentity(t *testing.T) {
	clock := newFakeClock()
	g := suite.NewRunIDGenerator(clock)

	original := g.Next("retried-test", 1, 0)
	retry := g.Next("retried-test", 1, 1)

	if original == retry {
		t.Errorf(
			"Next(%q, 1, 0) = %q and Next(%q, 1, 1) = %q are identical — "+
				"the retry must receive a distinct identity so it gets its own sandbox "+
				"and its own log folder rather than re-entering the corrupted one",
			"retried-test", original, "retried-test", retry,
		)
	}
}

// TestRunIDGenerator_DifferentTestsGetDistinctIdentities verifies that two
// different tests, scheduled under the same frozen clock and the same
// repetition number and attempt number, do not collide.
func TestRunIDGenerator_DifferentTestsGetDistinctIdentities(t *testing.T) {
	clock := newFakeClock()
	g := suite.NewRunIDGenerator(clock)

	alpha := g.Next("test-alpha", 1, 0)
	beta := g.Next("test-beta", 1, 0)

	if alpha == beta {
		t.Errorf(
			"two different tests at the same (repetition=1, attempt=0) under a frozen clock both produced %q — "+
				"distinct tests must receive distinct identities",
			alpha,
		)
	}
}

// TestRunIDGenerator_MaxRunsPerSuite_IsExactly65536 pins the capacity constant
// to 2^16 — the number of four-hex-digit ordinals the external format contract
// permits. Any change to the constant forces this test to fail first, making
// the author acknowledge the format-contract consequence explicitly.
func TestRunIDGenerator_MaxRunsPerSuite_IsExactly65536(t *testing.T) {
	const want = 1 << 16
	if suite.MaxRunsPerSuite != want {
		t.Errorf(
			"MaxRunsPerSuite = %d, want %d (2^16 — fixed by the external format contract's "+
				"four hex digits of suffix; changing it changes what the logger bundle can attribute)",
			suite.MaxRunsPerSuite, want,
		)
	}
}

// TestRunIDGenerator_SafeForConcurrentUse verifies that many goroutines calling
// Next simultaneously produce no data races and no identity collisions. This is
// the concurrent-scheduler scenario: under a bound above 1, many repetitions
// request their run identity at nearly the same instant.
//
// Run with -race to catch synchronisation gaps. A collision here means two runs
// write into the same log folder and each attributes only part of its cost.
func TestRunIDGenerator_SafeForConcurrentUse(t *testing.T) {
	const goroutines = 64
	clock := newFakeClock() // frozen — all goroutines see the same instant
	g := suite.NewRunIDGenerator(clock)

	ids := make([]string, goroutines)
	var wg sync.WaitGroup
	wg.Add(goroutines)
	for i := 0; i < goroutines; i++ {
		i := i
		go func() {
			defer wg.Done()
			ids[i] = g.Next(fmt.Sprintf("concurrent-test-%03d", i), 1, 0)
		}()
	}
	wg.Wait()

	for i, id := range ids {
		if !domain.ValidRunID(id) {
			t.Errorf("goroutine %d: Next produced %q which is not ValidRunID-shaped", i, id)
		}
	}

	seen := make(map[string]int, goroutines)
	for i, id := range ids {
		if prev, dup := seen[id]; dup {
			t.Errorf(
				"identity collision: goroutine %d and goroutine %d both produced %q",
				prev, i, id,
			)
		}
		seen[id] = i
	}
}
