package app_test

// update_model_threading_test.go verifies Stage 3: threading of deployed model selections
// through the Update flow.
//
// The Update flow must:
//   - Build a model selection map from the probed deployed state
//   - Feed this map into plan.Input.Models (so the planner receives it)
//   - Feed the same map into buildContent (so the transform preserves the model key)
//   - Produce regenerated content that preserves the model ID found in the deployed file
//   - Not ask any model-selection questions (QTierModel, QAgentModel)
//   - Not persist any tier model mappings to UserConfig
//
// Tests marked "will FAIL against the current implementation" are in TDD RED phase.
// They will pass once I3.2 and I3.3 are implemented.

import (
	"context"
	"strings"
	"testing"

	"mosaic-deploy/internal/app"
	"mosaic-deploy/internal/app/interactiontest"
	"mosaic-deploy/internal/deploy"
	"mosaic-deploy/internal/domain"
	"mosaic-deploy/internal/plan"
)

// ---------------------------------------------------------------------------
// Spy / capturing executor (local to this file)
// ---------------------------------------------------------------------------

// contentCapturingExecutor intercepts deploy.ExecRequest.Content and calls it for every
// agent plan item, recording the generated bytes by agent key. This allows tests to inspect
// what the content-generation callback produces without requiring real file writes.
type contentCapturingExecutor struct {
	capturedContents map[string][]byte // agentKey → bytes from Content callback
	result           deploy.ExecResult
}

func (e *contentCapturingExecutor) Execute(ctx context.Context, req deploy.ExecRequest) (deploy.ExecResult, error) {
	e.capturedContents = make(map[string][]byte)
	for _, item := range req.Plan.Items {
		if item.Ref.Kind == domain.ArtifactAgent {
			content, err := req.Content(item)
			if err == nil {
				e.capturedContents[item.Ref.Key] = content
			}
		}
	}
	return e.result, nil
}

// ---------------------------------------------------------------------------
// Shared helpers (local to this file)
// ---------------------------------------------------------------------------

// newModelKeyModule returns a stubHarnessModule whose descriptor declares "model" as the
// frontmatter key for model selection. Tests that verify content-generation behaviour
// require the harness to emit a model key; the default stub module does not.
func newModelKeyModule() *stubHarnessModule {
	return &stubHarnessModule{
		ref: minimalHarness,
		descriptor: domain.HarnessDescriptor{
			ID:          "stub-harness",
			DisplayName: "Stub Harness",
			Models:      domain.ModelCatalog{IDs: []string{"model-a", "model-b"}},
			Frontmatter: domain.FrontmatterSpec{ModelKey: "model"},
		},
	}
}

// ---------------------------------------------------------------------------
// T3.2 — plan.Input.Models populated from deployed state
// ---------------------------------------------------------------------------

// TestUpdate_AgentWithDeployedModel_PlanInputModelsIsNonNil verifies that when the deployed
// workspace contains an agent file with an embedded model, plan.Input.Models is non-nil
// when the planner is called. This test will FAIL against the current implementation which
// leaves Models nil.
func TestUpdate_AgentWithDeployedModel_PlanInputModelsIsNonNil(t *testing.T) {
	ws := t.TempDir()

	// Write a deployed agent file that embeds a model ID in its frontmatter.
	agentContent := []byte("---\nversion: \"1.0\"\nmodel: \"claude-opus-4-5\"\n---\nAgent body.\n")
	writeTempFile(t, ws, "test-runner.md", agentContent)

	// Use a harness module that declares "model" as the model frontmatter key, so the probe
	// extracts the ModelID from the deployed file.
	mod := newModelKeyModule()

	spy := &spyPlanner{response: domain.Plan{
		Mode: domain.ModeUpdateWorkspace, Harness: minimalHarness, WorkspacePath: ws,
	}}
	stub := interactiontest.NewBuilder().Build()
	deps, _ := newBaseDeps(t, stub)
	deps.Registry = newMinimalRegistry(mod)
	deps.Planner = spy
	svc := app.New(deps)

	_, err := svc.Update(context.Background(), app.UpdateRequest{
		HarnessID:       "stub-harness",
		WorkspacePath:   ws,
		AddWorkflowIDs:  []string{"quick-fix"},
		AutoConfirmPlan: true,
	})
	if err != nil {
		t.Fatalf("Update: %v", err)
	}

	captured := spy.lastCaptured(t)
	if captured.Models == nil {
		t.Error("plan.Input.Models is nil; the Update flow must build a model selection map " +
			"from the probed deployed state and pass it to the planner when at least one agent " +
			"file carries a non-empty embedded ModelID")
	}
}

// TestUpdate_AgentWithDeployedModel_PlanInputModelsHasResolvedEntry verifies that the model
// selection in plan.Input.Models for an agent whose deployed file carries a model is resolved.
// This test will FAIL against the current implementation.
func TestUpdate_AgentWithDeployedModel_PlanInputModelsHasResolvedEntry(t *testing.T) {
	ws := t.TempDir()
	agentContent := []byte("---\nversion: \"1.0\"\nmodel: \"claude-opus-4-5\"\n---\nAgent body.\n")
	writeTempFile(t, ws, "test-runner.md", agentContent)

	mod := newModelKeyModule()
	spy := &spyPlanner{response: domain.Plan{
		Mode: domain.ModeUpdateWorkspace, Harness: minimalHarness, WorkspacePath: ws,
	}}
	stub := interactiontest.NewBuilder().Build()
	deps, _ := newBaseDeps(t, stub)
	deps.Registry = newMinimalRegistry(mod)
	deps.Planner = spy
	svc := app.New(deps)

	_, err := svc.Update(context.Background(), app.UpdateRequest{
		HarnessID:       "stub-harness",
		WorkspacePath:   ws,
		AddWorkflowIDs:  []string{"quick-fix"},
		AutoConfirmPlan: true,
	})
	if err != nil {
		t.Fatalf("Update: %v", err)
	}

	captured := spy.lastCaptured(t)
	if captured.Models == nil {
		t.Fatal("plan.Input.Models is nil; prerequisite for resolved-selection check")
	}

	sel, ok := captured.Models["test-runner"]
	if !ok {
		t.Fatal("plan.Input.Models[\"test-runner\"] is absent; prerequisite for resolved-selection check")
	}
	if !sel.Resolved() {
		t.Errorf("plan.Input.Models[\"test-runner\"].Resolved() = false, want true; "+
			"the selection built from a deployed file must satisfy Resolved() so the planner "+
			"does not emit a spurious GapNoModel gap for an agent that already has a model")
	}
}

// TestUpdate_AgentWithDeployedModel_PlanInputModelsModelIDVerbatim verifies that the model
// ID in plan.Input.Models is the verbatim value from the deployed file's frontmatter.
// This test will FAIL against the current implementation.
func TestUpdate_AgentWithDeployedModel_PlanInputModelsModelIDVerbatim(t *testing.T) {
	ws := t.TempDir()
	const deployedModelID = "claude-opus-4-5"
	agentContent := []byte("---\nversion: \"1.0\"\nmodel: \"" + deployedModelID + "\"\n---\nAgent body.\n")
	writeTempFile(t, ws, "test-runner.md", agentContent)

	mod := newModelKeyModule()
	spy := &spyPlanner{response: domain.Plan{
		Mode: domain.ModeUpdateWorkspace, Harness: minimalHarness, WorkspacePath: ws,
	}}
	stub := interactiontest.NewBuilder().Build()
	deps, _ := newBaseDeps(t, stub)
	deps.Registry = newMinimalRegistry(mod)
	deps.Planner = spy
	svc := app.New(deps)

	_, err := svc.Update(context.Background(), app.UpdateRequest{
		HarnessID:       "stub-harness",
		WorkspacePath:   ws,
		AddWorkflowIDs:  []string{"quick-fix"},
		AutoConfirmPlan: true,
	})
	if err != nil {
		t.Fatalf("Update: %v", err)
	}

	captured := spy.lastCaptured(t)
	if captured.Models == nil {
		t.Fatal("plan.Input.Models is nil; prerequisite for ModelID verbatim check")
	}

	sel, ok := captured.Models["test-runner"]
	if !ok {
		t.Fatal("plan.Input.Models[\"test-runner\"] is absent; prerequisite for ModelID verbatim check")
	}
	if sel.ModelID != deployedModelID {
		t.Errorf("plan.Input.Models[\"test-runner\"].ModelID = %q, want %q; "+
			"the model ID must be carried verbatim from the deployed file without normalisation",
			sel.ModelID, deployedModelID)
	}
}

// TestUpdate_AgentWithDeployedModel_PlanInputModelsOriginIsDeployed verifies that the Origin
// of the model selection in plan.Input.Models is OriginDeployed, marking provenance as
// "read back from a deployed file". This test will FAIL against the current implementation.
func TestUpdate_AgentWithDeployedModel_PlanInputModelsOriginIsDeployed(t *testing.T) {
	ws := t.TempDir()
	agentContent := []byte("---\nversion: \"1.0\"\nmodel: \"claude-opus-4-5\"\n---\nAgent body.\n")
	writeTempFile(t, ws, "test-runner.md", agentContent)

	mod := newModelKeyModule()
	spy := &spyPlanner{response: domain.Plan{
		Mode: domain.ModeUpdateWorkspace, Harness: minimalHarness, WorkspacePath: ws,
	}}
	stub := interactiontest.NewBuilder().Build()
	deps, _ := newBaseDeps(t, stub)
	deps.Registry = newMinimalRegistry(mod)
	deps.Planner = spy
	svc := app.New(deps)

	_, err := svc.Update(context.Background(), app.UpdateRequest{
		HarnessID:       "stub-harness",
		WorkspacePath:   ws,
		AddWorkflowIDs:  []string{"quick-fix"},
		AutoConfirmPlan: true,
	})
	if err != nil {
		t.Fatalf("Update: %v", err)
	}

	captured := spy.lastCaptured(t)
	if captured.Models == nil {
		t.Fatal("plan.Input.Models is nil; prerequisite for Origin check")
	}

	sel, ok := captured.Models["test-runner"]
	if !ok {
		t.Fatal("plan.Input.Models[\"test-runner\"] is absent; prerequisite for Origin check")
	}
	if sel.Origin != domain.OriginDeployed {
		t.Errorf("plan.Input.Models[\"test-runner\"].Origin = %q, want %q (OriginDeployed); "+
			"the origin must identify the deployed file as the source of the model selection",
			sel.Origin, domain.OriginDeployed)
	}
}

// TestUpdate_AgentWithNoDeployedModel_AbsentFromPlanInputModels verifies that an agent whose
// deployed file exists but carries no model ID is absent from plan.Input.Models, so
// downstream gap evaluation still flags it for missing model.
func TestUpdate_AgentWithNoDeployedModel_AbsentFromPlanInputModels(t *testing.T) {
	ws := t.TempDir()
	// Deployed file present but no "model" key in frontmatter.
	agentContent := []byte("---\nversion: \"1.0\"\n---\nAgent without model.\n")
	writeTempFile(t, ws, "test-runner.md", agentContent)

	mod := newModelKeyModule()
	spy := &spyPlanner{response: domain.Plan{
		Mode: domain.ModeUpdateWorkspace, Harness: minimalHarness, WorkspacePath: ws,
	}}
	stub := interactiontest.NewBuilder().Build()
	deps, _ := newBaseDeps(t, stub)
	deps.Registry = newMinimalRegistry(mod)
	deps.Planner = spy
	svc := app.New(deps)

	_, err := svc.Update(context.Background(), app.UpdateRequest{
		HarnessID:       "stub-harness",
		WorkspacePath:   ws,
		AddWorkflowIDs:  []string{"quick-fix"},
		AutoConfirmPlan: true,
	})
	if err != nil {
		t.Fatalf("Update: %v", err)
	}

	captured := spy.lastCaptured(t)
	// When the agent has no deployed model, it must be absent from Models so downstream
	// gap evaluation can still flag it. A nil map (no models at all) is also acceptable here
	// since the agent is absent by definition.
	if captured.Models != nil {
		if sel, ok := captured.Models["test-runner"]; ok && sel.Resolved() {
			t.Errorf("plan.Input.Models[\"test-runner\"] = {ModelID: %q, Origin: %q}, want absent or unresolved; "+
				"an agent with no deployed model must not appear as resolved in plan.Input.Models so "+
				"gap evaluation can still flag it for missing model",
				sel.ModelID, sel.Origin)
		}
	}
}

// ---------------------------------------------------------------------------
// T3.2 — same map must feed content generation
// ---------------------------------------------------------------------------

// TestUpdate_AgentWithDeployedModel_GeneratedContentPreservesModel verifies that the content
// generated by the Update flow for an agent whose deployed file carries a model ID also
// contains that model ID. This is the key end-to-end invariant: the deployed model selection
// must reach buildContent so the transform writes the model key rather than stripping it.
//
// This test will FAIL against the current implementation because buildContent is called with
// nil for the models argument, causing the transform to treat the model as unresolved and
// omit the model key from the generated content.
func TestUpdate_AgentWithDeployedModel_GeneratedContentPreservesModel(t *testing.T) {
	ws := t.TempDir()

	// Write a deployed agent file that embeds a model ID.
	deployedContent := []byte("---\nversion: \"1.0\"\nmodel: \"claude-opus-4-5\"\n---\nAgent body.\n")
	writeTempFile(t, ws, "test-runner.md", deployedContent)

	// Configure a harness with ModelKey so the transform knows which frontmatter key to write.
	mod := newModelKeyModule()

	// The stub planner returns an ActionUpdate item for test-runner so the Content callback
	// is exercised for an agent whose deployed file carries a model.
	updateItem := domain.PlanItem{
		Ref:        domain.ArtifactRef{Kind: domain.ArtifactAgent, Key: "test-runner"},
		TargetPath: "test-runner.md",
		Action:     domain.ActionUpdate,
	}

	capExec := &contentCapturingExecutor{
		result: deploy.ExecResult{DeploymentRoot: ws},
	}

	stub := interactiontest.NewBuilder().AnswerReview(true).Build()
	deps, _ := newBaseDeps(t, stub)
	deps.Registry = newMinimalRegistry(mod)
	deps.Planner = &stubPlanner{plan: domain.Plan{
		Mode:          domain.ModeUpdateWorkspace,
		Harness:       minimalHarness,
		WorkspacePath: ws,
		Items:         []domain.PlanItem{updateItem},
	}}
	deps.Executor = capExec
	svc := app.New(deps)

	_, err := svc.Update(context.Background(), app.UpdateRequest{
		HarnessID:       "stub-harness",
		WorkspacePath:   ws,
		AddWorkflowIDs:  []string{"quick-fix"},
		AutoConfirmPlan: true,
	})
	if err != nil {
		t.Fatalf("Update: %v", err)
	}

	// Assert — the generated content for test-runner must include the deployed model ID.
	content, ok := capExec.capturedContents["test-runner"]
	if !ok {
		t.Fatal("Content callback was not called for test-runner; " +
			"the capturing executor must have invoked Content(item) for the ActionUpdate plan item")
	}
	if !strings.Contains(string(content), "claude-opus-4-5") {
		t.Errorf("generated content for test-runner does not contain the deployed model ID %q; "+
			"the Update flow must thread the deployed model selection into buildContent so the "+
			"transform writes model: %q rather than stripping the model key.\n"+
			"generated content:\n%s",
			"claude-opus-4-5", "claude-opus-4-5", content)
	}
}

// TestUpdate_AgentWithDeployedModel_PlanInputAndContentReceiveSameModelID verifies that
// plan.Input.Models and the content generated by the Content callback both carry the same
// model ID. This confirms that the same map instance feeds both paths rather than two
// independently derived values, upholding the critical consistency invariant from the design.
//
// This test will FAIL against the current implementation.
func TestUpdate_AgentWithDeployedModel_PlanInputAndContentReceiveSameModelID(t *testing.T) {
	ws := t.TempDir()

	const deployedModelID = "claude-sonnet-4"
	deployedContent := []byte("---\nversion: \"1.0\"\nmodel: \"" + deployedModelID + "\"\n---\nAgent body.\n")
	writeTempFile(t, ws, "test-runner.md", deployedContent)

	mod := newModelKeyModule()

	updateItem := domain.PlanItem{
		Ref:        domain.ArtifactRef{Kind: domain.ArtifactAgent, Key: "test-runner"},
		TargetPath: "test-runner.md",
		Action:     domain.ActionUpdate,
	}

	capExec := &contentCapturingExecutor{
		result: deploy.ExecResult{DeploymentRoot: ws},
	}

	// Use a plannerAndCapture that both records the plan.Input and returns a plan with items.
	type plannerAndCapture struct {
		spyPlanner
	}

	spy := &spyPlanner{response: domain.Plan{
		Mode:          domain.ModeUpdateWorkspace,
		Harness:       minimalHarness,
		WorkspacePath: ws,
		Items:         []domain.PlanItem{updateItem},
	}}

	stub := interactiontest.NewBuilder().AnswerReview(true).Build()
	deps, _ := newBaseDeps(t, stub)
	deps.Registry = newMinimalRegistry(mod)
	deps.Planner = spy
	deps.Executor = capExec
	svc := app.New(deps)

	_, err := svc.Update(context.Background(), app.UpdateRequest{
		HarnessID:       "stub-harness",
		WorkspacePath:   ws,
		AddWorkflowIDs:  []string{"quick-fix"},
		AutoConfirmPlan: true,
	})
	if err != nil {
		t.Fatalf("Update: %v", err)
	}

	// Check plan.Input.Models has the correct model ID.
	captured := spy.lastCaptured(t)
	var planModelID string
	if captured.Models != nil {
		if sel, ok := captured.Models["test-runner"]; ok {
			planModelID = sel.ModelID
		}
	}
	if planModelID != deployedModelID {
		t.Errorf("plan.Input.Models[\"test-runner\"].ModelID = %q, want %q; "+
			"the planner must receive the deployed model ID", planModelID, deployedModelID)
	}

	// Check generated content also has the correct model ID.
	content, ok := capExec.capturedContents["test-runner"]
	if !ok {
		t.Fatal("Content callback was not called for test-runner; prerequisite for consistency check")
	}
	if !strings.Contains(string(content), deployedModelID) {
		t.Errorf("generated content does not contain the deployed model ID %q; "+
			"both plan.Input.Models and the content-generation step must carry the same model ID.\n"+
			"generated content:\n%s", deployedModelID, content)
	}
}

// ---------------------------------------------------------------------------
// T3.3 — no model-selection interaction
// ---------------------------------------------------------------------------

// TestUpdate_NoQTierModelAsked verifies that the Update flow never asks QTierModel, even when
// deployed agents carry embedded models. The Update flow is non-interactive with respect to
// model selection: models are read back from deployed files, not prompted.
func TestUpdate_NoQTierModelAsked(t *testing.T) {
	ws := t.TempDir()
	agentContent := []byte("---\nversion: \"1.0\"\nmodel: \"claude-opus-4-5\"\n---\nAgent body.\n")
	writeTempFile(t, ws, "test-runner.md", agentContent)

	mod := newModelKeyModule()
	stub := interactiontest.NewBuilder().AnswerReview(true).Build()
	deps, _ := newBaseDeps(t, stub)
	deps.Registry = newMinimalRegistry(mod)
	deps.Planner = &stubPlanner{plan: domain.Plan{
		Mode: domain.ModeUpdateWorkspace, Harness: minimalHarness, WorkspacePath: ws,
	}}
	svc := app.New(deps)

	_, _ = svc.Update(context.Background(), app.UpdateRequest{
		HarnessID:       "stub-harness",
		WorkspacePath:   ws,
		AddWorkflowIDs:  []string{"quick-fix"},
		AutoConfirmPlan: true,
	})

	for _, call := range stub.Calls() {
		if call.ID == domain.QTierModel {
			t.Errorf("QTierModel was asked (subject: %q) during Update; the Update flow must "+
				"not prompt for tier model selection — models are read back from deployed "+
				"files non-interactively and must never trigger a model question", call.Subject)
		}
	}
}

// TestUpdate_NoQAgentModelAsked verifies that the Update flow never asks QAgentModel, even
// when deployed agents carry embedded models. Model selection in the Update flow is
// non-interactive: it reads back from deployed files only.
func TestUpdate_NoQAgentModelAsked(t *testing.T) {
	ws := t.TempDir()
	agentContent := []byte("---\nversion: \"1.0\"\nmodel: \"claude-opus-4-5\"\n---\nAgent body.\n")
	writeTempFile(t, ws, "test-runner.md", agentContent)

	mod := newModelKeyModule()
	stub := interactiontest.NewBuilder().AnswerReview(true).Build()
	deps, _ := newBaseDeps(t, stub)
	deps.Registry = newMinimalRegistry(mod)
	deps.Planner = &stubPlanner{plan: domain.Plan{
		Mode: domain.ModeUpdateWorkspace, Harness: minimalHarness, WorkspacePath: ws,
	}}
	svc := app.New(deps)

	_, _ = svc.Update(context.Background(), app.UpdateRequest{
		HarnessID:       "stub-harness",
		WorkspacePath:   ws,
		AddWorkflowIDs:  []string{"quick-fix"},
		AutoConfirmPlan: true,
	})

	for _, call := range stub.Calls() {
		if call.ID == domain.QAgentModel {
			t.Errorf("QAgentModel was asked (subject: %q) during Update; the Update flow must "+
				"not prompt for per-agent model selection — models are read back from deployed "+
				"files and must never trigger a model question", call.Subject)
		}
	}
}

// TestUpdate_NoModelQuestionsAsked_EvenWhenDeployedFileLacksModel verifies that the Update
// flow still asks no model questions even when the deployed agent file carries no embedded
// model. The Update flow never prompts for models — if the deployed file has no model, the
// agent is flagged via a gap, not prompted interactively.
func TestUpdate_NoModelQuestionsAsked_EvenWhenDeployedFileLacksModel(t *testing.T) {
	ws := t.TempDir()
	// Write a deployed file with NO model key.
	agentContent := []byte("---\nversion: \"1.0\"\n---\nAgent without model.\n")
	writeTempFile(t, ws, "test-runner.md", agentContent)

	mod := newModelKeyModule()
	stub := interactiontest.NewBuilder().AnswerReview(true).Build()
	deps, _ := newBaseDeps(t, stub)
	deps.Registry = newMinimalRegistry(mod)
	deps.Planner = &stubPlanner{plan: domain.Plan{
		Mode: domain.ModeUpdateWorkspace, Harness: minimalHarness, WorkspacePath: ws,
	}}
	svc := app.New(deps)

	_, _ = svc.Update(context.Background(), app.UpdateRequest{
		HarnessID:       "stub-harness",
		WorkspacePath:   ws,
		AddWorkflowIDs:  []string{"quick-fix"},
		AutoConfirmPlan: true,
	})

	for _, call := range stub.Calls() {
		if call.ID == domain.QTierModel || call.ID == domain.QAgentModel {
			t.Errorf("model question %q (subject: %q) was asked during Update; "+
				"the Update flow must NEVER ask model-selection questions — "+
				"even when no deployed model is found, the flow must use gap reporting "+
				"rather than interactive model selection", call.ID, call.Subject)
		}
	}
}

// TestUpdate_NoTierModelsPersisted_WhenDeployedModelExists verifies that the Update flow
// does not call UserConfigStore.Save with any tier model data. Model selections read back
// from deployed files are per-run only and must not be persisted to user configuration.
func TestUpdate_NoTierModelsPersisted_WhenDeployedModelExists(t *testing.T) {
	ws := t.TempDir()
	agentContent := []byte("---\nversion: \"1.0\"\nmodel: \"claude-opus-4-5\"\n---\nAgent body.\n")
	writeTempFile(t, ws, "test-runner.md", agentContent)

	mod := newModelKeyModule()
	spyConfig := &spyUserConfig{}
	stub := interactiontest.NewBuilder().AnswerReview(true).Build()
	deps, _ := newBaseDeps(t, stub)
	deps.Registry = newMinimalRegistry(mod)
	deps.UserConfig = spyConfig
	deps.Planner = &stubPlanner{plan: domain.Plan{
		Mode: domain.ModeUpdateWorkspace, Harness: minimalHarness, WorkspacePath: ws,
	}}
	svc := app.New(deps)

	_, _ = svc.Update(context.Background(), app.UpdateRequest{
		HarnessID:       "stub-harness",
		WorkspacePath:   ws,
		AddWorkflowIDs:  []string{"quick-fix"},
		AutoConfirmPlan: true,
	})

	for _, saved := range spyConfig.saved {
		if len(saved.TierModels) > 0 {
			t.Errorf("UserConfig.Save was called with TierModels = %v; "+
				"the Update flow must not persist tier model mappings — "+
				"deployed model selections are transient and must not be written to user config",
				saved.TierModels)
		}
	}
}

// TestUpdate_NoTierModelsPersisted_WhenDeployedFileLacksModel verifies that even when the
// deployed agent file carries no model, the Update flow does not try to persist any model
// resolution to UserConfig. The Update flow never resolves models interactively.
func TestUpdate_NoTierModelsPersisted_WhenDeployedFileLacksModel(t *testing.T) {
	ws := t.TempDir()
	agentContent := []byte("---\nversion: \"1.0\"\n---\nAgent without model.\n")
	writeTempFile(t, ws, "test-runner.md", agentContent)

	mod := newModelKeyModule()
	spyConfig := &spyUserConfig{}
	stub := interactiontest.NewBuilder().AnswerReview(true).Build()
	deps, _ := newBaseDeps(t, stub)
	deps.Registry = newMinimalRegistry(mod)
	deps.UserConfig = spyConfig
	deps.Planner = &stubPlanner{plan: domain.Plan{
		Mode: domain.ModeUpdateWorkspace, Harness: minimalHarness, WorkspacePath: ws,
	}}
	svc := app.New(deps)

	_, _ = svc.Update(context.Background(), app.UpdateRequest{
		HarnessID:       "stub-harness",
		WorkspacePath:   ws,
		AddWorkflowIDs:  []string{"quick-fix"},
		AutoConfirmPlan: true,
	})

	for _, saved := range spyConfig.saved {
		if len(saved.TierModels) > 0 {
			t.Errorf("UserConfig.Save was called with TierModels = %v; "+
				"the Update flow must not persist any tier model mappings even when agents "+
				"have no deployed model — use gap reporting, not interactive resolution",
				saved.TierModels)
		}
	}
}

// ---------------------------------------------------------------------------
// T3.2 supplement — plan.Input reference type invariant
// ---------------------------------------------------------------------------

// TestUpdate_PlanInputModelsAndContentShareConsistentModelID verifies that the model ID
// ultimately seen by the planner and the model ID written into the generated content are
// consistent with each other. If they were derived independently, a bug could cause the
// planner to suppress a gap while the transform still strips the model key.
//
// Setup: single agent with an embedded model; use both a spyPlanner (to capture Models)
// and a contentCapturingExecutor (to inspect generated bytes). Both must show the same ID.
//
// This test will FAIL against the current implementation.
func TestUpdate_PlanInputModelsAndContentShareConsistentModelID(t *testing.T) {
	ws := t.TempDir()
	const deployedModelID = "claude-haiku-4"

	deployedContent := []byte("---\nversion: \"1.0\"\nmodel: \"" + deployedModelID + "\"\n---\nAgent.\n")
	writeTempFile(t, ws, "test-runner.md", deployedContent)

	mod := newModelKeyModule()

	updateItem := domain.PlanItem{
		Ref:        domain.ArtifactRef{Kind: domain.ArtifactAgent, Key: "test-runner"},
		TargetPath: "test-runner.md",
		Action:     domain.ActionUpdate,
	}

	capExec := &contentCapturingExecutor{result: deploy.ExecResult{DeploymentRoot: ws}}
	spy := &spyPlanner{response: domain.Plan{
		Mode:    domain.ModeUpdateWorkspace,
		Harness: minimalHarness,
		WorkspacePath: ws,
		Items:   []domain.PlanItem{updateItem},
	}}

	stub := interactiontest.NewBuilder().AnswerReview(true).Build()
	deps, _ := newBaseDeps(t, stub)
	deps.Registry = newMinimalRegistry(mod)
	deps.Planner = spy
	deps.Executor = capExec
	svc := app.New(deps)

	_, err := svc.Update(context.Background(), app.UpdateRequest{
		HarnessID:       "stub-harness",
		WorkspacePath:   ws,
		AddWorkflowIDs:  []string{"quick-fix"},
		AutoConfirmPlan: true,
	})
	if err != nil {
		t.Fatalf("Update: %v", err)
	}

	captured := spy.lastCaptured(t)

	// plan.Input.Models must carry the deployed model ID.
	planHasModel := false
	if captured.Models != nil {
		if sel, ok := captured.Models["test-runner"]; ok && sel.ModelID == deployedModelID {
			planHasModel = true
		}
	}
	if !planHasModel {
		t.Errorf("plan.Input.Models[\"test-runner\"].ModelID != %q; "+
			"planner must receive the deployed model ID", deployedModelID)
	}

	// Generated content must also carry the deployed model ID.
	content, ok := capExec.capturedContents["test-runner"]
	if !ok {
		t.Fatal("Content callback was not called for test-runner; prerequisite for consistency check")
	}
	contentHasModel := strings.Contains(string(content), deployedModelID)
	if !contentHasModel {
		t.Errorf("generated content does not contain the deployed model ID %q; "+
			"the content-generation step and the planner must use the same model selection "+
			"(critical consistency invariant: same map instance feeds both paths).\n"+
			"generated content:\n%s", deployedModelID, content)
	}
}

// Ensure the plan package is used (it is referenced transitively via spyPlanner, which is
// defined in probe_wiring_test.go and uses plan.Input). This blank import guard keeps the
// compiler from complaining if a future refactor removes the indirect use.
var _ = plan.PlannedPaths(nil)
