/**
 * handlers_tools.ts — Tool call event handlers.
 *
 * HIGH-FREQUENCY PATH: these handlers must not make SDK calls, transcript reads,
 * or directory scans. They resolve the event sink from the in-memory correlation
 * store and append one event line.
 *
 * Maps:
 *   - tool.execute.before -> tool_call_start
 *   - tool.execute.after  -> tool_call_end
 */

import { currentTimestamp } from "./core.js";
import type {
  HandlerDependencies,
  ToolBeforeInput,
  ToolBeforeOutput,
  ToolAfterInput,
} from "./handlers_session.js";

// ---------------------------------------------------------------------------
// Handler factory
// ---------------------------------------------------------------------------

/**
 * Create tool call event handlers.
 *
 * The call_id is generated by handleToolBefore and stored in the correlation
 * store so that handleToolAfter can emit the matching call_id on tool_call_end.
 * This ensures both events for the same tool execution carry the same call_id,
 * as required by MosaicLogFormat.md.
 */
export function createToolHandlers(deps: HandlerDependencies): {
  /**
   * Handle tool.execute.before. Emits tool_call_start.
   * Routes to orchestrator or subagent event file based on sessionID lookup.
   */
  handleToolBefore: (input: ToolBeforeInput, output: ToolBeforeOutput) => Promise<void>;

  /**
   * Handle tool.execute.after. Emits tool_call_end.
   */
  handleToolAfter: (input: ToolAfterInput) => Promise<void>;
} {
  const { store, paths, buildEvent, appendEvent, fallbackCallId } = deps;

  async function handleToolBefore(
    input: ToolBeforeInput,
    output: ToolBeforeOutput,
  ): Promise<void> {
    const sessionId = input.sessionID;
    const toolName = input.tool || "";

    const ts = currentTimestamp();
    const runId = store.getRunId(sessionId);
    const sink = store.resolveEventSink(sessionId, paths);

    // Generate and store call_id so handleToolAfter can use the same value.
    const callId = fallbackCallId(toolName);
    store.storePendingCallId(sessionId, callId);

    await appendEvent(
      sink,
      buildEvent(
        "tool_call_start",
        { sessionId, runId, timestamp: ts },
        {
          call_id: callId,
          tool_name: toolName,
          tool_input: output.args,
        },
      ),
    );
  }

  async function handleToolAfter(input: ToolAfterInput): Promise<void> {
    const sessionId = input.sessionID;
    const toolName = input.tool || "";

    const ts = currentTimestamp();
    const runId = store.getRunId(sessionId);
    const sink = store.resolveEventSink(sessionId, paths);

    // Retrieve the call_id stored during handleToolBefore.
    // If missing (defensive: should not happen under normal serial execution),
    // generate a new fallback and accept that this tool_call_end won't correlate
    // with its tool_call_start rather than crashing.
    const callId = store.popPendingCallId(sessionId) ?? fallbackCallId(toolName);

    // tool_output may appear under different field names in the payload.
    // Access defensively with optional chaining.
    const toolOutput =
      (input as Record<string, unknown>)["output"] ??
      (input as Record<string, unknown>)["tool_output"] ??
      (input as Record<string, unknown>)["result"];

    await appendEvent(
      sink,
      buildEvent(
        "tool_call_end",
        { sessionId, runId, timestamp: ts },
        {
          call_id: callId,
          status: "success",
          tool_output: toolOutput,
        },
      ),
    );
  }

  return { handleToolBefore, handleToolAfter };
}
