package opencode_test

// Tests for correlation: the token generated by NewToken, planted into the
// call's arguments by PlantToken, and recovered from the echoed arguments by
// RecoverToken. See ContractsDesign.md's "AgentTest: Correlation" for the
// full contract.
//
// Two properties matter and are each easy to lose: the token must survive
// the pre-to-post round trip, and it must reveal nothing — the subject can
// see the call it is being handed, so a readable, test-flavoured token would
// tell it that it is being tested and invalidate every verdict the tool
// produces.
//
// NewToken, PlantToken and RecoverToken are still the stubs in correlation.go
// at the time these tests are written (T7.3); every test below is expected
// to fail against those stubs until the translation pass (I7.4) implements
// them for real.

import (
	"strings"
	"testing"

	"mosaic-agent-test/internal/harness/opencode"
)

// bannedTokenVocabulary mirrors internal/harness/contract's own banned list:
// a token or field name carrying any of these words tips the subject off
// that it is being exercised.
var bannedTokenVocabulary = []string{"test", "mosaic", "stub", "fake", "mock", "harness"}

func TestNewToken_ContainsNoTestRevealingVocabulary(t *testing.T) {
	token := opencode.NewToken()
	lower := strings.ToLower(token)
	for _, banned := range bannedTokenVocabulary {
		if strings.Contains(lower, banned) {
			t.Errorf("NewToken: %q contains test-revealing vocabulary %q", token, banned)
		}
	}
}

func TestNewToken_IsNonEmpty(t *testing.T) {
	if opencode.NewToken() == "" {
		t.Errorf("NewToken: returned an empty token")
	}
}

func TestNewToken_SuccessiveCallsAreUnguessablyDifferent(t *testing.T) {
	seen := map[string]bool{}
	for i := 0; i < 20; i++ {
		token := opencode.NewToken()
		if seen[token] {
			t.Fatalf("NewToken: produced the same token twice (%q) across %d calls; a repeatable token is guessable", token, i+1)
		}
		seen[token] = true
	}
}

func TestPlantToken_EmbedsTokenRecoverably(t *testing.T) {
	token := opencode.NewToken()
	args := opencode.TaskToolArgs{SubagentType: "Worker", Prompt: "please respond with the scripted stub content"}

	planted := opencode.PlantToken(args, token)

	recovered, ok := opencode.RecoverToken(planted)
	if !ok {
		t.Fatalf("RecoverToken: ok = false after PlantToken; the token must be recoverable from what was planted")
	}
	if recovered != token {
		t.Errorf("RecoverToken: recovered %q, want the planted token %q", recovered, token)
	}
}

func TestPlantToken_PreservesRestOfArgs(t *testing.T) {
	token := opencode.NewToken()
	args := opencode.TaskToolArgs{SubagentType: "Worker", Description: "do the work", Prompt: "please respond with the scripted stub content"}

	planted := opencode.PlantToken(args, token)

	if planted.SubagentType != args.SubagentType {
		t.Errorf("PlantToken: SubagentType = %q, want unchanged %q", planted.SubagentType, args.SubagentType)
	}
	if planted.Description != args.Description {
		t.Errorf("PlantToken: Description = %q, want unchanged %q", planted.Description, args.Description)
	}
}

func TestRecoverToken_NoTokenPresentReturnsFalseNotError(t *testing.T) {
	// A call this tool never rewrote — a legitimate condition, not a
	// malformed one.
	args := opencode.TaskToolArgs{SubagentType: "Worker", Prompt: "an ordinary, un-stubbed prompt"}

	_, ok := opencode.RecoverToken(args)
	if ok {
		t.Errorf("RecoverToken: ok = true for arguments this tool never planted a token into")
	}
}

func TestCorrelationRoundTrip_TokenSurvivesAndKeysBothRecords(t *testing.T) {
	tokenA := opencode.NewToken()
	tokenB := opencode.NewToken()

	argsA := opencode.PlantToken(opencode.TaskToolArgs{SubagentType: "Worker", Prompt: "first call"}, tokenA)
	argsB := opencode.PlantToken(opencode.TaskToolArgs{SubagentType: "Reviewer", Prompt: "second call"}, tokenB)

	recoveredA, okA := opencode.RecoverToken(argsA)
	recoveredB, okB := opencode.RecoverToken(argsB)
	if !okA || !okB {
		t.Fatalf("RecoverToken: ok = (%v, %v), want both true", okA, okB)
	}
	if recoveredA == recoveredB {
		t.Fatalf("RecoverToken: two independently planted tokens recovered as the same value (%q); they must key their own invocation, not collide", recoveredA)
	}
	if recoveredA != tokenA || recoveredB != tokenB {
		t.Errorf("RecoverToken: recovered (%q, %q), want (%q, %q)", recoveredA, recoveredB, tokenA, tokenB)
	}
}
