package opencode

// Plugin generation. See ContractsDesign.md's "AgentTest: Bridge and Plugin
// Generation" for the full "Generated plugin contract" this renders.
//
// GeneratePlugin's runtime behaviour cannot be verified without a real
// `opencode` binary, which is out of scope by explicit constraint. Its
// logic is kept thin enough that its correctness is legible by reading the
// rendered module itself.

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// PluginFileName is the generated plugin's file name inside the plugins
// directory. Named so it is recognisable in a sandbox listing and so
// Provision's foreign-plugin scan can tell its own file from someone else's.
const PluginFileName = "mosaic-interceptor.ts"

// GeneratePlugin renders the interception plugin module for one sandbox.
// Pure over its inputs: it returns bytes and writes nothing, and the same
// bridges always render byte-identical content.
func GeneratePlugin(pre, post Bridge) ([]byte, error) {
	toolName, err := json.Marshal(InterceptedToolName)
	if err != nil {
		return nil, fmt.Errorf("opencode: encoding intercepted tool name: %w", err)
	}
	preExec, err := json.Marshal(pre.Executable)
	if err != nil {
		return nil, fmt.Errorf("opencode: encoding pre-invocation bridge executable: %w", err)
	}
	preArgs, err := json.Marshal(pre.Args)
	if err != nil {
		return nil, fmt.Errorf("opencode: encoding pre-invocation bridge args: %w", err)
	}
	postExec, err := json.Marshal(post.Executable)
	if err != nil {
		return nil, fmt.Errorf("opencode: encoding post-invocation bridge executable: %w", err)
	}
	postArgs, err := json.Marshal(post.Args)
	if err != nil {
		return nil, fmt.Errorf("opencode: encoding post-invocation bridge args: %w", err)
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, pluginTemplate, toolName, preExec, preArgs, postExec, postArgs)
	return buf.Bytes(), nil
}

// pluginTemplate is the generated plugin module. It registers exactly two
// hooks:
//
//   - tool.execute.before runs synchronously with respect to the call: it
//     awaits the interceptor's reply before returning, because rewriting a
//     call's arguments after it has already run means nothing. It can
//     rewrite output.args on an "allow" decision and can throw on a "deny"
//     decision — this harness's only block mechanism.
//   - tool.execute.after is observational only. It never assigns onto
//     output: after-hook result mutation is deliberately unused, because
//     such mutations are confirmed not to be honoured downstream and the
//     hook's runtime output shape is inconsistent between two undocumented
//     forms.
//
// Known blind spots, stated as limitations rather than worked around: tool
// calls routed through MCP never trigger these hooks, and calls made by
// agents OpenCode itself spawned as subagents may not be intercepted
// either.
const pluginTemplate = `// Code generated by mosaic-agent-test. DO NOT EDIT.
//
// Bridges OpenCode's tool hooks to the mosaic-agent-test interceptor.
//
// Known limitations (documented here rather than worked around):
//   - Hooks do not fire for tool calls routed through MCP.
//   - Hooks may not intercept tool calls made by agents OpenCode itself
//     spawned as subagents.
//   - tool.execute.after's ability to mutate its result is deliberately
//     unused: such mutations are confirmed not to be honoured downstream,
//     and the hook's runtime output shape is inconsistent between two
//     undocumented forms.

import { spawnSync } from "node:child_process";

const INTERCEPTED_TOOL = %s;

const PRE_EXECUTABLE = %s;
const PRE_ARGS = %s;
const POST_EXECUTABLE = %s;
const POST_ARGS = %s;

// runInterceptor invokes the interceptor binary and waits for its reply. A
// broken or silent interceptor degrades to null rather than throwing or
// blocking: a stub harness that blocks real work under a fabricated refusal
// is worse than one that lets the call through and fails the test honestly.
async function runInterceptor(executable, args, payload) {
  try {
    const result = spawnSync(executable, args, {
      input: JSON.stringify(payload),
      encoding: "utf8",
    });
    if (result.error || result.status !== 0 || !result.stdout) {
      return null;
    }
    return JSON.parse(result.stdout);
  } catch {
    return null;
  }
}

export default async function MosaicInterceptor(ctx) {
  return {
    "tool.execute.before": async (input, output) => {
      if (input.tool !== INTERCEPTED_TOOL) {
        return;
      }
      const reply = await runInterceptor(PRE_EXECUTABLE, PRE_ARGS, {
        hook_event_name: "tool.execute.before",
        sessionID: input.sessionID,
        callID: input.callID,
        tool: input.tool,
        args: output.args,
      });
      if (!reply) {
        return;
      }
      if (reply.decision === "deny") {
        throw new Error(reply.reason || "mosaic-agent-test interceptor denied this call");
      }
      if (reply.decision === "allow" && reply.updatedArgs) {
        Object.assign(output.args, reply.updatedArgs);
      }
    },
    "tool.execute.after": async (input, output) => {
      if (input.tool !== INTERCEPTED_TOOL) {
        return;
      }
      // Observational only: nothing in this handler ever touches the real
      // result.
      await runInterceptor(POST_EXECUTABLE, POST_ARGS, {
        hook_event_name: "tool.execute.after",
        sessionID: input.sessionID,
        callID: input.callID,
        tool: input.tool,
        args: input.args,
        output,
      });
    },
  };
}
`
