/**
 * handlers_tools.ts — Tool call event handlers.
 *
 * HIGH-FREQUENCY PATH: these handlers must not make SDK calls, transcript reads,
 * or directory scans. They resolve the event sink from the in-memory correlation
 * store and append one event line.
 *
 * Maps:
 *   - tool.execute.before -> tool_call_start
 *   - tool.execute.after  -> tool_call_end
 */

import { currentTimestamp } from "./core.js";
import { extractInstanceId, extractRunId } from "./runstate.js";
import type {
  HandlerDependencies,
  ToolBeforeInput,
  ToolBeforeOutput,
  ToolAfterInput,
  ToolAfterOutput,
} from "./handlers_session.js";

// ---------------------------------------------------------------------------
// ToolOutcome
// ---------------------------------------------------------------------------

/**
 * Defensively derived outcome from an after-hook payload whose shape is
 * unconfirmed. Status and error detail are omitted when the payload signals
 * neither success nor failure — this is strictly better than the old
 * unconditional "success" literal, because an omitted optional field is
 * spec-legal and honest, unlike a false claim.
 */
export interface ToolOutcome {
  /** Omitted entirely when the payload signals neither success nor failure. */
  status?: "success" | "error";
  /** Failure detail, present only alongside status "error". */
  error?: string;
  /** Whatever the payload yielded as the tool's output, from the probe cascade. */
  toolOutput?: unknown;
}

/**
 * Derive a tool call's outcome from the after-hook payload.
 * Probes the payload defensively under several plausible field names rather than
 * committing to one. Returns "error" with detail only on a clearly-signalled
 * failure; "success" only on a clearly-signalled success; omits status entirely
 * when the payload supports no conclusion. Exported for direct testing.
 *
 * Signal detection priority:
 *   1. A non-empty string `error` field → status "error" with captured detail
 *   2. `status === "error"` → status "error" (with detail if `error` field present)
 *   3. `status === "success"` → status "success"
 *   4. `success === true` → status "success"
 *   5. Anything else (including undefined output) → no status (omit the field)
 */
export function deriveToolOutcome(
  _input: ToolAfterInput,
  output: ToolAfterOutput | undefined,
): ToolOutcome {
  if (output == null || typeof output !== "object") {
    return {};
  }
  const raw = output as Record<string, unknown>;

  const errorField = typeof raw["error"] === "string" && raw["error"] !== ""
    ? raw["error"]
    : undefined;
  const statusField = raw["status"];
  const successField = raw["success"];

  // Explicit error signal from `error` field or `status === "error"`
  if (errorField !== undefined || statusField === "error") {
    return {
      status: "error",
      ...(errorField !== undefined ? { error: errorField } : {}),
    };
  }

  // Explicit success signal from `status === "success"` or `success === true`
  if (statusField === "success" || successField === true) {
    return { status: "success" };
  }

  // No recognizable outcome signal — omit status entirely
  return {};
}

// ---------------------------------------------------------------------------
// Handler factory
// ---------------------------------------------------------------------------

/**
 * Create tool call event handlers.
 *
 * The call_id is generated by handleToolBefore and stored in the correlation
 * store so that handleToolAfter can emit the matching call_id on tool_call_end.
 * This ensures both events for the same tool execution carry the same call_id,
 * as required by MosaicLogFormat.md.
 */
export function createToolHandlers(deps: HandlerDependencies): {
  /**
   * Handle tool.execute.before. Emits tool_call_start.
   * Routes to orchestrator or subagent event file based on sessionID lookup.
   */
  handleToolBefore: (input: ToolBeforeInput, output: ToolBeforeOutput) => Promise<void>;

  /**
   * Handle tool.execute.after. Emits tool_call_end with a defensively derived
   * outcome status. Accepts an optional output parameter for the after-hook payload.
   */
  handleToolAfter: (input: ToolAfterInput, output?: ToolAfterOutput) => Promise<void>;

  /**
   * Close an open `task` dispatch call from a signal other than the after-hook.
   * Called by invocation-end handling when the dispatched subagent's invocation
   * ends. A no-op when the call is already closed (idempotent). Emits
   * tool_call_end carrying the original call_id with no tool_output.
   */
  closeDispatchCall: (childSessionId: string) => Promise<void>;
} {
  const { store, paths, buildEvent, appendEvent, fallbackCallId } = deps;

  async function handleToolBefore(
    input: ToolBeforeInput,
    output: ToolBeforeOutput,
  ): Promise<void> {
    const sessionId = input.sessionID;
    const toolName = input.tool || "";

    const ts = currentTimestamp();
    const runId = store.getRunId(sessionId);
    const sink = store.resolveEventSink(sessionId, paths);

    // Use OpenCode's native callID when available; fall back to generated value.
    const callId = input.callID ?? fallbackCallId(toolName);

    // Register in the call-id keyed registry so parallel tool calls in one session
    // each retain independent correlation handles. When the after-hook arrives
    // without a native callID, closeToolCallBySession looks up this entry by
    // session+toolName so the two events always carry the same call_id.
    store.registerToolCall({
      callId,
      sessionId,
      toolName,
      isDispatch: toolName === "task",
      startedAt: ts,
    });

    // When this is a `task` dispatch, capture identity from the args and queue it
    // as a pending dispatch for the subagent session that will be created under
    // this parent. No SDK calls, transcript reads, or directory scans are made here.
    if (toolName === "task") {
      const promptText = typeof output.args["prompt"] === "string"
        ? output.args["prompt"]
        : undefined;
      const subagentType = typeof output.args["subagent_type"] === "string"
        ? output.args["subagent_type"]
        : undefined;
      store.pushPendingDispatch(sessionId, {
        callId,
        parentSessionId: sessionId,
        agentInstanceId: extractInstanceId(promptText),
        agentType: subagentType,
        runId: extractRunId(promptText),
        prompt: promptText,
        dispatchedAt: ts,
      });
    }

    await appendEvent(
      sink,
      buildEvent(
        "tool_call_start",
        { sessionId, runId, timestamp: ts },
        {
          call_id: callId,
          tool_name: toolName,
          tool_input: output.args,
        },
      ),
    );
  }

  async function handleToolAfter(input: ToolAfterInput, output?: ToolAfterOutput): Promise<void> {
    const sessionId = input.sessionID;
    const toolName = input.tool || "";

    const ts = currentTimestamp();
    const runId = store.getRunId(sessionId);
    const sink = store.resolveEventSink(sessionId, paths);

    let callId: string;

    if (input.callID !== undefined) {
      // Keyed-by-callId path: close exactly once for idempotency.
      // When the call was already closed (real after-hook and synthetic closure
      // race), closeToolCall returns undefined — return immediately so only one
      // tool_call_end event is ever emitted per call.
      const entry = store.closeToolCall(input.callID);
      if (!entry) return;
      callId = entry.callId;
    } else {
      // No native callID: look up by session+tool in the keyed registry.
      // Finds and closes the first matching in-flight entry, preserving
      // call_id correlation with the corresponding tool_call_start. Falls back
      // to a generated id only when no matching start was registered (e.g. the
      // after-hook fires for a call whose before-hook was not observed).
      const entry = store.closeToolCallBySession(sessionId, toolName);
      callId = entry?.callId ?? fallbackCallId(toolName);
    }

    // Derive outcome from the after-hook output. When no output is supplied
    // (handleToolAfter called with one argument), default to "success" to
    // preserve the pre-existing behavior for callers that do not pass output.
    const outcome: ToolOutcome =
      output !== undefined ? deriveToolOutcome(input, output) : { status: "success" };

    // tool_output may appear under different field names in the payload.
    // Access defensively with optional chaining.
    const toolOutput =
      (input as Record<string, unknown>)["output"] ??
      (input as Record<string, unknown>)["tool_output"] ??
      (input as Record<string, unknown>)["result"];

    await appendEvent(
      sink,
      buildEvent(
        "tool_call_end",
        { sessionId, runId, timestamp: ts },
        {
          call_id: callId,
          status: outcome.status,      // undefined → omitted by buildEvent
          error: outcome.error,        // undefined → omitted by buildEvent
          tool_output: toolOutput,
        },
      ),
    );
  }

  /**
   * Synthetic dispatch closure: close the open `task` dispatch call for a child
   * session from the invocation-end signal rather than the real after-hook.
   * A no-op when no dispatch is open for this child session. Idempotent:
   * if the real after-hook already closed the call, this is a no-op.
   *
   * The emitted tool_call_end carries no tool_output because the synthetic path
   * has no output payload — only the real after-hook path has the actual output.
   */
  async function closeDispatchCall(childSessionId: string): Promise<void> {
    // Look up the still-open dispatch call for this child session.
    // Returns undefined when: (a) no dispatchCallId recorded, or (b) the call was
    // already closed by the real after-hook — both cases are silent no-ops.
    const dispatchCall = store.openDispatchCallFor(childSessionId);
    if (!dispatchCall) return;

    // Close exactly once: if the real after-hook won the race between openDispatchCallFor
    // and closeToolCall, closeToolCall returns undefined and we bail without emitting.
    const entry = store.closeToolCall(dispatchCall.callId);
    if (!entry) return;

    // Emit tool_call_end on the parent session's stream (where the dispatch originated).
    const parentSessionId = entry.sessionId;
    const ts = currentTimestamp();
    const runId = store.getRunId(parentSessionId);
    const sink = store.resolveEventSink(parentSessionId, paths);

    await appendEvent(
      sink,
      buildEvent(
        "tool_call_end",
        { sessionId: parentSessionId, runId, timestamp: ts },
        {
          call_id: entry.callId,
          // No tool_output — synthetic closure has no output payload
        },
      ),
    );
  }

  return { handleToolBefore, handleToolAfter, closeDispatchCall };
}
