package deploy_test

// todofile_test.go covers TODO file write behavior (ExecResult.TodoFilePath).
//
// After a normal run (DryRun=false), Execute writes a MOSAIC-DEPLOYMENT-TODO.md file to
// the workspace root and sets ExecResult.TodoFilePath to its absolute path.
//
// The file must contain:
//   - run-level metadata from ExecRequest.TodoMeta (e.g. harness name, workspace path).
//   - pre-collected items supplied via ExecRequest.TodoItems, which originate from the
//     transform and plan phases upstream of the executor. The executor calls TodoItems()
//     once at write time — after all per-item Content callbacks have completed — so items
//     added to the backing collector during Execute are included.
//   - gaps generated by the executor itself during the run (e.g. skipped file gaps from
//     conflict decisions, fallback-location gaps when the workspace is unwritable).

import (
	"context"
	"os"
	"strings"
	"testing"

	"mosaic-deploy/internal/deploy"
	"mosaic-deploy/internal/domain"
	"mosaic-deploy/internal/manifest"
	"mosaic-deploy/internal/todo"
)

// TestTodoFile_PathIsPopulated verifies that ExecResult.TodoFilePath is non-empty after a
// normal run. A non-empty value indicates the executor wrote the file and recorded its path.
func TestTodoFile_PathIsPopulated(t *testing.T) {
	workspace := t.TempDir()
	mosaicRoot := t.TempDir()

	item := newAgentItem("runner", "agents/runner.md", domain.ActionCreate)
	req := deploy.ExecRequest{
		Plan:       newPlan(workspace, item),
		MosaicRoot: mosaicRoot,
		Content:    fixedContent([]byte("content")),
	}

	ex := deploy.NewExecutor(manifest.NewStore(), newSpyLogger(), newSpyCollector())
	result, err := ex.Execute(context.Background(), req)
	if err != nil {
		t.Fatalf("Execute: %v", err)
	}

	if result.TodoFilePath == "" {
		t.Error("ExecResult.TodoFilePath is empty; it must be set to the absolute path of the written TODO file")
	}
}

// TestTodoFile_FileExistsOnDisk verifies that the file referenced by ExecResult.TodoFilePath
// actually exists on disk after a normal run.
func TestTodoFile_FileExistsOnDisk(t *testing.T) {
	workspace := t.TempDir()
	mosaicRoot := t.TempDir()

	item := newAgentItem("runner", "agents/runner.md", domain.ActionCreate)
	req := deploy.ExecRequest{
		Plan:       newPlan(workspace, item),
		MosaicRoot: mosaicRoot,
		Content:    fixedContent([]byte("content")),
	}

	ex := deploy.NewExecutor(manifest.NewStore(), newSpyLogger(), newSpyCollector())
	result, err := ex.Execute(context.Background(), req)
	if err != nil {
		t.Fatalf("Execute: %v", err)
	}

	if result.TodoFilePath == "" {
		t.Fatal("ExecResult.TodoFilePath is empty; cannot verify file existence")
	}
	if !fileExistsAt(t, result.TodoFilePath) {
		t.Errorf("TODO file not found at %q; it must be written to disk after a normal run", result.TodoFilePath)
	}
}

// TestTodoFile_PreCollectedItemsAppearInFile verifies that TodoItem values supplied via
// ExecRequest.TodoItems appear in the written file. These items originate from the transform
// and plan phases; the executor must include them alongside any gaps it generates itself.
// The executor must obtain the items by calling TodoItems() at write time, not by reading
// a snapshot captured before Execute was called.
func TestTodoFile_PreCollectedItemsAppearInFile(t *testing.T) {
	workspace := t.TempDir()
	mosaicRoot := t.TempDir()

	preCollected := domain.TodoItem{
		Category: domain.TodoModels,
		Subject:  "agent-needing-model",
		Detail:   "No model was selected for this agent during planning",
	}

	item := newAgentItem("runner", "agents/runner.md", domain.ActionCreate)
	req := deploy.ExecRequest{
		Plan:       newPlan(workspace, item),
		MosaicRoot: mosaicRoot,
		Content:    fixedContent([]byte("content")),
		TodoItems:  func() []domain.TodoItem { return []domain.TodoItem{preCollected} },
	}

	ex := deploy.NewExecutor(manifest.NewStore(), newSpyLogger(), newSpyCollector())
	result, err := ex.Execute(context.Background(), req)
	if err != nil {
		t.Fatalf("Execute: %v", err)
	}
	if result.TodoFilePath == "" {
		t.Fatal("ExecResult.TodoFilePath is empty; cannot verify file content")
	}

	content, err := os.ReadFile(result.TodoFilePath)
	if err != nil {
		t.Fatalf("read TODO file at %q: %v", result.TodoFilePath, err)
	}
	if !strings.Contains(string(content), preCollected.Subject) {
		t.Errorf("TODO file does not contain pre-collected item subject %q; "+
			"executor must call TodoItems() at write time and render the returned items;\nfile content:\n%s",
			preCollected.Subject, content)
	}
}

// TestTodoFile_ExecutorGapAppearsInFile verifies that gaps the executor generates during
// the run appear in the written TODO file. A DecisionSkip conflict produces a GapSkippedFile
// gap; the rendered file must reference the skipped item.
func TestTodoFile_ExecutorGapAppearsInFile(t *testing.T) {
	workspace := t.TempDir()
	mosaicRoot := t.TempDir()
	targetPath := "agents/runner.md"

	writeExisting(t, workspace, targetPath, []byte("local content"))

	item := newConflictItem("runner", targetPath)
	req := deploy.ExecRequest{
		Plan:       newPlan(workspace, item),
		MosaicRoot: mosaicRoot,
		Content:    fixedContent([]byte("new content")),
		Conflicts:  map[string]domain.ConflictDecision{targetPath: domain.DecisionSkip},
	}

	ex := deploy.NewExecutor(manifest.NewStore(), newSpyLogger(), newSpyCollector())
	result, err := ex.Execute(context.Background(), req)
	if err != nil {
		t.Fatalf("Execute: %v", err)
	}
	if result.TodoFilePath == "" {
		t.Fatal("ExecResult.TodoFilePath is empty; cannot verify file content")
	}

	content, err := os.ReadFile(result.TodoFilePath)
	if err != nil {
		t.Fatalf("read TODO file at %q: %v", result.TodoFilePath, err)
	}
	// A skipped conflict emits a GapSkippedFile gap whose Subject is the agent key or target
	// path. The rendered file must include a reference to the skipped item.
	if !strings.Contains(string(content), "runner") {
		t.Errorf("TODO file does not reference the skipped item %q;\nfile content:\n%s",
			targetPath, content)
	}
}

// TestTodoFile_TodoMetaEmbeddedInFile verifies that run-level metadata from
// ExecRequest.TodoMeta (at minimum the harness name) appears in the written file header.
func TestTodoFile_TodoMetaEmbeddedInFile(t *testing.T) {
	workspace := t.TempDir()
	mosaicRoot := t.TempDir()

	meta := todo.Meta{
		Harness:       "test-harness",
		WorkspacePath: workspace,
		Mode:          domain.ModeDeployWorkspace,
	}

	item := newAgentItem("runner", "agents/runner.md", domain.ActionCreate)
	req := deploy.ExecRequest{
		Plan:       newPlan(workspace, item),
		MosaicRoot: mosaicRoot,
		Content:    fixedContent([]byte("content")),
		TodoMeta:   meta,
	}

	ex := deploy.NewExecutor(manifest.NewStore(), newSpyLogger(), newSpyCollector())
	result, err := ex.Execute(context.Background(), req)
	if err != nil {
		t.Fatalf("Execute: %v", err)
	}
	if result.TodoFilePath == "" {
		t.Fatal("ExecResult.TodoFilePath is empty; cannot verify file content")
	}

	content, err := os.ReadFile(result.TodoFilePath)
	if err != nil {
		t.Fatalf("read TODO file at %q: %v", result.TodoFilePath, err)
	}
	if !strings.Contains(string(content), meta.Harness) {
		t.Errorf("TODO file does not contain harness name %q from TodoMeta;\nfile content:\n%s",
			meta.Harness, content)
	}
}
